import { Campaign } from "../types/Campaign";
import { BackendResponse } from "./BackendResponse";
// import httpClient from "./HttpClient";
// const api_route = "campaigns";

export const CampaignService = {
    async getPendingCampaigns() {
        const response = [
                {
                    id: '1',
                    title: 'Campaña de Ayuda a Niños',
                    category: 'Salud',
                    imageUrl: '/images/campaign1.jpg',
                    goal: 10000,
                    daysLeft: 10,
                    endDate: new Date('2023-12-31'),
                    description: 'Ayudamos a niños en situación vulnerable proporcionándoles atención médica y educación.',
                    status: 'active',
                    donors: 245,
                    amountRaised: 7500,
                    creator: 'Juan Pérez',
                    creatorImageUrl: '/images/creator1.jpg',
                    creatorBio: 'Activista social con más de 10 años de experiencia en proyectos comunitarios.',
                    walletAddress: '0x1234567890abcdef1234567890abcdef12345678',
                    isVerified: true,
                    fullDescription: 'Esta campaña busca recaudar fondos para proporcionar atención médica y educación a niños',
                    createdAt: new Date('2023-01-01')
                },
                {
                    id: '2',
                    title: 'Protección del Medio Ambiente',
                    category: 'Medio Ambiente',
                    imageUrl: '/images/campaign2.jpg',
                    goal: 8000,
                    daysLeft: 5,
                    endDate: new Date('2023-09-15'),
                    description: 'Proyecto para la conservación de bosques nativos y reforestación de áreas degradadas.',
                    status: 'active',
                    donors: 128,
                    amountRaised: 6200,
                    creator: 'María González',
                    creatorImageUrl: '/images/creator2.jpg',
                    creatorBio: 'Bióloga especializada en conservación ambiental.',
                    walletAddress: '0xabcdef1234567890abcdef1234567890abcdef12',
                    isVerified: true,
                    fullDescription: 'Esta campaña busca proteger los bosques nativos mediante proyectos de reforestación y conservación.',
                    createdAt: new Date('2023-06-01')
                },
                {
                    id: '3',
                    title: 'Educación para Todos',
                    category: 'Educación',
                    imageUrl: '/images/campaign3.jpg',
                    goal: 15000,
                    daysLeft: 20,
                    endDate: new Date('2024-03-15'),
                    description: 'Construcción de aulas y provisión de materiales educativos para escuelas rurales.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Carlos Mendoza',
                    creatorImageUrl: '/images/creator3.jpg',
                    creatorBio: 'Educador con 15 años de experiencia en zonas rurales.',
                    walletAddress: '0xdef1234567890abcdef1234567890abcdef123456',
                    isVerified: false,
                    fullDescription: 'Esta campaña busca mejorar la infraestructura educativa en comunidades rurales.',
                    createdAt: new Date('2024-01-15')
                },
                {
                    id: '4',
                    title: 'Refugio para Animales Abandonados',
                    category: 'Animales',
                    imageUrl: '/images/campaign4.jpg',
                    goal: 12000,
                    daysLeft: 25,
                    endDate: new Date('2024-04-01'),
                    description: 'Creación de un refugio para perros y gatos abandonados con atención veterinaria.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Ana Rodriguez',
                    creatorImageUrl: '/images/creator4.jpg',
                    creatorBio: 'Veterinaria especializada en bienestar animal.',
                    walletAddress: '0x234567890abcdef1234567890abcdef1234567890',
                    isVerified: false,
                    fullDescription: 'Refugio que proporcionará hogar temporal y atención médica a animales en situación de calle.',
                    createdAt: new Date('2024-01-20')
                },
                {
                    id: '5',
                    title: 'Apoyo a Emprendedores Juveniles',
                    category: 'Emprendimiento',
                    imageUrl: '/images/campaign5.jpg',
                    goal: 20000,
                    daysLeft: 30,
                    endDate: new Date('2024-05-01'),
                    description: 'Programa de capacitación y microcréditos para jóvenes emprendedores.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Roberto Silva',
                    creatorImageUrl: '/images/creator5.jpg',
                    creatorBio: 'Consultor en desarrollo empresarial y mentor de startups.',
                    walletAddress: '0x567890abcdef1234567890abcdef1234567890abc',
                    isVerified: false,
                    fullDescription: 'Programa integral que incluye formación, mentoría y financiamiento para jóvenes emprendedores.',
                    createdAt: new Date('2024-02-01')
                },
                {
                    id: '6',
                    title: 'Agua Potable para Comunidades Rurales',
                    category: 'Infraestructura',
                    imageUrl: '/images/campaign6.jpg',
                    goal: 25000,
                    daysLeft: 40,
                    endDate: new Date('2024-06-01'),
                    description: 'Instalación de sistemas de agua potable en comunidades sin acceso a servicios básicos.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Elena Vargas',
                    creatorImageUrl: '/images/creator6.jpg',
                    creatorBio: 'Ingeniera civil especializada en proyectos de infraestructura social.',
                    walletAddress: '0x890abcdef1234567890abcdef1234567890abcdef',
                    isVerified: false,
                    fullDescription: 'Proyecto que llevará agua potable a más de 500 familias en zonas rurales.',
                    createdAt: new Date('2024-02-10')
                },
                {
                    id: '7',
                    title: 'Talleres de Arte para Niños',
                    category: 'Arte y Cultura',
                    imageUrl: '/images/campaign7.jpg',
                    goal: 8500,
                    daysLeft: 15,
                    endDate: new Date('2024-03-30'),
                    description: 'Programa de talleres artísticos para niños en situación de vulnerabilidad social.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Patricia Morales',
                    creatorImageUrl: '/images/creator7.jpg',
                    creatorBio: 'Artista plástica y educadora con enfoque en terapia artística.',
                    walletAddress: '0xabcdef1234567890abcdef1234567890abcdef78',
                    isVerified: false,
                    fullDescription: 'Talleres que combinan arte y terapia para el desarrollo emocional de los niños.',
                    createdAt: new Date('2024-02-15')
                },
                {
                    id: '8',
                    title: 'Comedor Comunitario',
                    category: 'Alimentación',
                    imageUrl: '/images/campaign8.jpg',
                    goal: 18000,
                    daysLeft: 35,
                    endDate: new Date('2024-05-15'),
                    description: 'Apertura de un comedor comunitario para familias en situación de inseguridad alimentaria.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Miguel Torres',
                    creatorImageUrl: '/images/creator8.jpg',
                    creatorBio: 'Chef profesional comprometido con la seguridad alimentaria comunitaria.',
                    walletAddress: '0xcdef1234567890abcdef1234567890abcdef1234',
                    isVerified: false,
                    fullDescription: 'Comedor que proporcionará alimentos nutritivos a familias de bajos recursos.',
                    createdAt: new Date('2024-02-20')
                },
                {
                    id: '9',
                    title: 'Tecnología para Adultos Mayores',
                    category: 'Tecnología',
                    imageUrl: '/images/campaign9.jpg',
                    goal: 10000,
                    daysLeft: 28,
                    endDate: new Date('2024-04-20'),
                    description: 'Programa de alfabetización digital para adultos mayores.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Sandra López',
                    creatorImageUrl: '/images/creator9.jpg',
                    creatorBio: 'Especialista en tecnología educativa y gerontología.',
                    walletAddress: '0xef1234567890abcdef1234567890abcdef123456',
                    isVerified: false,
                    fullDescription: 'Curso integral para enseñar el uso de dispositivos móviles y computadoras a adultos mayores.',
                    createdAt: new Date('2024-02-25')
                },
                {
                    id: '10',
                    title: 'Huerta Urbana Sostenible',
                    category: 'Sostenibilidad',
                    imageUrl: '/images/campaign10.jpg',
                    goal: 14000,
                    daysLeft: 22,
                    endDate: new Date('2024-04-10'),
                    description: 'Creación de huertas urbanas para promover la agricultura sostenible en la ciudad.',
                    status: 'revision',
                    donors: 0,
                    amountRaised: 0,
                    creator: 'Francisco Herrera',
                    creatorImageUrl: '/images/creator10.jpg',
                    creatorBio: 'Agrónomo especializado en permacultura urbana.',
                    walletAddress: '0x1234567890abcdef1234567890abcdef12345abc',
                    isVerified: false,
                    fullDescription: 'Proyecto que establecerá espacios verdes productivos en áreas urbanas subutilizadas.',
                    createdAt: new Date('2024-03-01')
                }
            ]
        // return await httpClient.get<BackendResponse<Campaign[]>>(`${api_route}`);
        return { data: response } as BackendResponse<Campaign[]>;
    },
}
